- name: Update Apt
  sudo: yes
  command: apt-get update

- name: Add nice repository adding
  sudo: yes
  apt: pkg=python-software-properties

- name: Add NPM PPA
  sudo: yes
  command: add-apt-repository ppa:chris-lea/node.js -y

- name: Update Apt
  sudo: yes
  command: apt-get update

- name: Install packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes force=yes
  with_items:
      # Database
      - postgresql
      - libpq-dev # Required for Ansible to interact with postgres
      - python-psycopg2 # Required for Ansible to interact with postgres

      # Python Dev
      - python-dev
      - python-setuptools
      - python-virtualenv

      # Just nice
      - screen
      - vim
      - emacs
      - htop
      - ack-grep
      - virtualenvwrapper
      - curl

      # Dev tools
      - git
      - rake
      - nodejs
      - firefox
      - xvfb

- name: Set DISPLAY
  sudo: yes
  lineinfile: dest=/etc/profile regexp=DISPLAY= line=export DISPLAY=:10

- name: Set FF BIN
  sudo: yes
  lineinfile: dest=/etc/profile regexp=FIREFOX_BIN= line=export FIREFOX_BIN=/usr/bin/firefox 
      
- name: Add xvfb initscript
  sudo: yes
  copy: src=xvfb dest=/etc/init.d/xvfb

- name: Make initscript executable
  sudo: yes
  command: chmod +x /etc/init.d/xvfb
  notify:
    - Restart XVFB
      
- name: Allow password authentication for local socket users
  sudo: yes
  copy: src=pg_hba.conf dest=/etc/postgresql/9.1/main/pg_hba.conf force=yes
  notify:
      - Restart Postgres

- name: Setup Working Directories
  sudo: yes
  file: path=/usr/lib/ohc state=directory mode=777

- name: SSH | Find Git repo SSH host key
  shell: ssh-keyscan github.com
  register: git_repo_host_key

- name: SSH | Add Git repo host key to known_hosts file
  lineinfile: create=yes dest=/home/vagrant/.ssh/known_hosts line='{{ git_repo_host_key.stdout }}' state=present